from .e01_food_get_opensource import main as e01_get_opensource
from .e02_food_googleapi_text_search import main as e02_googleapi_text_search
from .e03_food_craw_googlemap_info import main as e03_craw_googlemap_info

from .t01_food_filter_new_row import main as t01_filter_new_row
from .t02_food_compare_name_and_add import main as t02_compare_name_and_add
from .t03_food_clean_openhours_name import main as t03_clean_openhours_name

from .l01_food_insert_into_and_update_mysql import main as l01_insert_into_and_update_mysql
